api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import (
    BartenderViewSet,
    BeerTypeViewSet,
    BreweryViewSet,
    IsBartenderView,
    ItemViewSet,
    LastModifiedView,
    PrintStatusView,
    TokenAuthView,
)

router = routers.DefaultRouter()
router.register(r"items", ItemViewSet, "items")
router.register(r"breweries", BreweryViewSet, "breweries")
router.register(r"beerTypes", BeerTypeViewSet)
router.register(r"bartenders", BartenderViewSet)

urlpatterns = [
    path("auth/", TokenAuthView.as_view(), name="token-auth"),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("last-modified/", LastModifiedView.as_view(), name="last-modified"),
    path("is-bartender/<username>/", IsBartenderView.as_view(), name="is_bartender"),
    path("print_status/<job_id>/", PrintStatusView.as_view(), name="print_status"),
]

urlpatterns += router.urls

udlejning/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from bartenders.models import Bartender


class UdlejningCommon(models.Model):
    class Meta:
        abstract = True

    PAYMENT_CHOICES = (
        ("EAN", _("EAN")),
        ("invoice", _("Faktura")),
        ("card", _("Kort i baren")),
    )

    dateFrom = models.DateTimeField(
        verbose_name=_("Start dato & tid"),
        help_text=_("Hvornår skal anlægget afhentes/stilles op?"),
    )
    dateTo = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name=_("Slut dato & tid"),
        help_text=_("Hvornår skal anlægget afleveres/pilles ned?"),
    )
    whoReserved = models.CharField(max_length=140, verbose_name=_("Hvem er I?"))

    contactEmail = models.EmailField(verbose_name=_("Email til kontaktperson"))
    contactPhone = models.IntegerField(
        verbose_name=_("Telefonnummer til kontaktperson"), blank=True, null=True
    )

    whoPays = models.CharField(
        max_length=140,
        verbose_name=_("Hvem betaler?"),
        help_text=_(
            "Hvem skal regningen sendes til? (Fulde navn på person, virksomhed eller organisation)"
        ),
    )
    paymentType = models.CharField(
        max_length=140,
        choices=PAYMENT_CHOICES,
        verbose_name=_("Betalingsform"),
        help_text=_("Hvordan bliver der betalt?"),
    )

    EANnumber = models.BigIntegerField(
        verbose_name=_("EAN-nummer"),
        blank=True,
        null=True,
        help_text=_("Skal kun angives, hvis der skal faktureres til et EAN-nummer"),
    )

    where = models.TextField(
        max_length=140,
        verbose_name=_("Lokation"),
        help_text=_("Hvor bliver arrangmentet afholdt?"),
    )
    expectedConsummation = models.TextField(
        max_length=2048,
        verbose_name=_("Forventet forbrug"),
        help_text=_(
            "Hvilke slags øl eller andre drikkevarer ønskes der og hvor mange fustager af hver type?"
        ),
    )
    comments = models.TextField(
        blank=True, max_length=1024, verbose_name=_("Kommentarer")
    )

    def __str__(self):
        return f"{self.dateFrom} {self.whoReserved}"


class Udlejning(UdlejningCommon):
    ASSOCIATION_CHOICES = (
        ("internal", _("Intern")),
        ("external", _("Ekstern")),
    )

    STATUS_CHOICES = (
        ("notsent", _("Regning ikke sendt")),
        ("sent", _("Regning sendt")),
        ("paid", _("Regning betalt")),
    )

    SYSTEM_CHOICES = (
        ("small", _("Lille")),
        ("medium", _("Mellem")),
    )

    draftBeerSystem = models.CharField(
        max_length=16,
        choices=SYSTEM_CHOICES,
        verbose_name=_("Fadølsanlæg"),
        help_text=_("Hvilket anlæg vil I låne?"),
    )
    association = models.CharField(
        max_length=16,
        choices=ASSOCIATION_CHOICES,
        blank=True,
        verbose_name=_("Tilknytning"),
    )
    actualConsummation = models.TextField(blank=True, verbose_name=_("Faktisk forbrug"))
    bartendersInCharge = models.ManyToManyField(Bartender, verbose_name=_("Ansvarlige"))
    billSendTo = models.CharField(
        max_length=140, blank=True, verbose_name=_("Send regning til")
    )
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default="notsent")
    invoice_number = models.CharField(
        max_length=32, blank=True, verbose_name=_("Fakturanummer")
    )
    total_price = models.DecimalField(
        max_digits=9 + 2,
        decimal_places=2,
        blank=True,
        null=True,
        verbose_name=_("Total pris"),
    )
    payment_due_date = models.DateField(
        blank=True, null=True, verbose_name=_("Betalingsdato")
    )

    class Meta:
        ordering = ("dateFrom",)
        verbose_name = _("Udlejning af fadølsanlæg")
        verbose_name_plural = _("Udlejning af fadølsanlæg")

    def is_with_user(self, bartender):
        return bartender in self.bartendersInCharge.all()


class UdlejningApplication(UdlejningCommon):
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("created",)
        verbose_name = _("Udlejningsansøgning")
        verbose_name_plural = _("Udlejningsansøgninger")

    def accept(self):
        common_fields = super()._meta.get_fields()
        value_dict = {f.name: getattr(self, f.name) for f in common_fields}
        u = Udlejning.objects.create(**value_dict)
        return u.pk


class UdlejningGrill(models.Model):
    dateFrom = models.DateTimeField(verbose_name=_("Start dato & tid"))
    dateTo = models.DateTimeField(
        blank=True, null=True, verbose_name=_("Slut dato & tid")
    )
    whoReserved = models.TextField(max_length=140, verbose_name=_("Hvem er I?"))
    where = models.TextField(
        max_length=140, null=True, default=None, verbose_name=_("Lokation")
    )
    contactInfo = models.CharField(max_length=140, verbose_name=_("Kontakt info"))
    comments = models.TextField(blank=True, verbose_name=_("Kommentarer"))
    bartendersInCharge = models.ManyToManyField(Bartender, verbose_name=_("Ansvarlige"))

    class Meta:
        verbose_name = _("Udlejning af grill")
        verbose_name_plural = _("Udlejning af grill")
        ordering = ("dateFrom",)

    def is_with_user(self, bartender):
        return bartender in self.bartendersInCharge.all()


class UdlejningProjector(models.Model):
    dateFrom = models.DateTimeField(verbose_name=_("Start dato & tid"))
    dateTo = models.DateTimeField(
        blank=True, null=True, verbose_name=_("Slut dato & tid")
    )
    whoReserved = models.TextField(max_length=140, verbose_name=_("Hvem er I?"))
    where = models.TextField(
        max_length=140, null=True, default=None, verbose_name=_("Lokation")
    )
    contactInfo = models.CharField(max_length=140, verbose_name=_("Kontakt info"))
    comments = models.TextField(blank=True, verbose_name=_("Kommentarer"))
    bartendersInCharge = models.ManyToManyField(Bartender, verbose_name=_("Ansvarlige"))

    class Meta:
        verbose_name = _("Udlejning af projektor")
        verbose_name_plural = _("Udlejning af projektor")
        ordering = ("dateFrom",)

    def is_with_user(self, bartender):
        return bartender in self.bartendersInCharge.all()


class UdlejningSpeakers(models.Model):
    dateFrom = models.DateTimeField(verbose_name=_("Start dato & tid"))
    dateTo = models.DateTimeField(
        blank=True, null=True, verbose_name=_("Slut dato & tid")
    )
    whoReserved = models.TextField(max_length=140, verbose_name=_("Hvem er I?"))
    where = models.TextField(
        max_length=140, null=True, default=None, verbose_name=_("Lokation")
    )
    contactInfo = models.CharField(max_length=140, verbose_name=_("Kontakt info"))
    comments = models.TextField(blank=True, verbose_name=_("Kommentarer"))
    bartendersInCharge = models.ManyToManyField(Bartender, verbose_name=_("Ansvarlige"))

    class Meta:
        verbose_name = _("Udlejning af højtaler")
        verbose_name_plural = _("Udlejning af højtalere")
        ordering = ("dateFrom",)

    def is_with_user(self, bartender):
        return bartender in self.bartendersInCharge.all()


class UdlejningBoardGameCart(models.Model):
    dateFrom = models.DateTimeField(verbose_name=_("Start dato & tid"))
    dateTo = models.DateTimeField(
        blank=True, null=True, verbose_name=_("Slut dato & tid")
    )
    whoReserved = models.TextField(max_length=140, verbose_name=_("Hvem er I?"))
    where = models.TextField(
        max_length=140, null=True, default=None, verbose_name=_("Lokation")
    )
    contactInfo = models.CharField(max_length=140, verbose_name=_("Kontakt info"))
    comments = models.TextField(blank=True, verbose_name=_("Kommentarer"))
    bartendersInCharge = models.ManyToManyField(Bartender, verbose_name=_("Ansvarlige"))

    class Meta:
        verbose_name = _("Udlejning af brætspilsvogn")
        verbose_name_plural = _("Udlejning af brætspilsvogn")
        ordering = ("dateFrom",)

    def is_with_user(self, bartender):
        return bartender in self.bartendersInCharge.all()


class UdlejningTent(models.Model):
    dateFrom = models.DateTimeField(verbose_name=_("Start dato & tid"))
    dateTo = models.DateTimeField(
        blank=True, null=True, verbose_name=_("Slut dato & tid")
    )
    whoReserved = models.TextField(max_length=140, verbose_name=_("Hvem er I?"))
    where = models.TextField(
        max_length=140, null=True, default=None, verbose_name=_("Lokation")
    )
    contactInfo = models.CharField(max_length=140, verbose_name=_("Kontakt info"))
    comments = models.TextField(blank=True, verbose_name=_("Kommentarer"))
    bartendersInCharge = models.ManyToManyField(Bartender, verbose_name=_("Ansvarlige"))

    class Meta:
        verbose_name = _("Udlejning af festtelt")
        verbose_name_plural = _("Udlejning af festtelt")
        ordering = ("dateFrom",)

    def is_with_user(self, bartender):
        return bartender in self.bartendersInCharge.all()

udlejning/forms.py
from urllib.parse import urljoin

from bootstrap_datepicker_plus.widgets import DateTimePickerInput
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Invisible
from django import forms
from django.conf import settings
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _

from fredagscafeen.email import send_template_email

from .models import UdlejningApplication


class UdlejningApplicationForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = UdlejningApplication
        fields = "__all__"
        widgets = {
            "dateFrom": DateTimePickerInput(),
            "dateTo": DateTimePickerInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["paymentType"].widget.attrs.update({"class": "form-control"})
        for name in self.fields:
            self.fields[name].required = name not in ["EANnumber", "comments"]

    def clean(self):
        super().clean()

        d_from = self.cleaned_data.get("dateFrom")
        d_to = self.cleaned_data.get("dateTo")

        if d_to and d_from and d_from > d_to:
            self.add_error(
                "dateTo", f'"Til" tidspunkt skal komme efter "fra" tidspunkt'
            )

    def send_email(self, pk):
        d = self.cleaned_data

        url = urljoin(
            settings.SELF_URL,
            reverse("admin:udlejning_udlejningapplication_change", args=(pk,)),
        )

        return send_template_email(
            subject=f'Ny anmodning om reservation af fadølsanlæg af {d["whoReserved"]}',
            body_template="""Dette er en automatisk email.

{whoReserved} har ansøgt om at låne et fadølsanlæg:
Dato: {dateFrom} til {dateTo}
Kontakt email: {contactEmail}
Kontakt telefonnummer: {contactPhone}
Betaler: {whoPays}
Betalingsform: {paymentType}
EAN-nummer: {EANnumber}
Lokation: {where}
Forventet forbrug: {expectedConsummation}
Kommentarer:
{comments}

Ansøgningen kan blive accepteret eller afvist i {link} ,
men husk at kontakte personen efter dette.
/snek""",
            text_format={"link": f"admin interfacet: {url}", **d},
            html_format={
                "link": mark_safe(f'<a href="{url}">admin interfacet</a>'),
                **d,
            },
            to=["udlejning@fredagscafeen.dk"],
        )

udlejning/views.py
import datetime

from django.conf import settings
from django.contrib import messages
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, ListView

from .forms import UdlejningApplicationForm
from .models import (
    Udlejning,
    UdlejningApplication,
    UdlejningBoardGameCart,
    UdlejningGrill,
    UdlejningProjector,
    UdlejningSpeakers,
    UdlejningTent,
)


class Udlejninger(CreateView):
    model = UdlejningApplication
    template_name = "udlejning.html"
    form_class = UdlejningApplicationForm
    success_url = "/udlejning/#"  # Don't scroll to form on success

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["udlejninger"] = Udlejning.objects.filter(
            dateFrom__gte=timezone.now() - datetime.timedelta(days=30),
        )
        return context

    def form_valid(self, form):
        # Call super to save instance
        response = super().form_valid(form)

        # Send email to best
        form.send_email(self.object.pk)
        messages.success(
            self.request,
            _("Din anmodning om at låne fadølsanlægget er modtaget."),
        )

        return response


class UdlejningerGrill(ListView):
    template_name = "udlejningGrill.html"
    allow_empty = True
    queryset = UdlejningGrill.objects.filter(
        dateFrom__gte=timezone.now() - datetime.timedelta(days=30)
    )
    context_object_name = "udlejningGrill"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class UdlejningerProjector(ListView):
    template_name = "udlejningProjector.html"
    allow_empty = True
    queryset = UdlejningProjector.objects.filter(
        dateFrom__gte=timezone.now() - datetime.timedelta(days=30)
    )
    context_object_name = "udlejningProjector"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class UdlejningerSpeakers(ListView):
    template_name = "udlejningSpeakers.html"
    allow_empty = True
    queryset = UdlejningSpeakers.objects.filter(
        dateFrom__gte=timezone.now() - datetime.timedelta(days=30)
    )
    context_object_name = "udlejningSpeakers"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class UdlejningerBoardGameCart(ListView):
    template_name = "udlejningBoardGameCart.html"
    allow_empty = True
    queryset = UdlejningBoardGameCart.objects.filter(
        dateFrom__gte=timezone.now() - datetime.timedelta(days=30)
    )
    context_object_name = "udlejningBoardGameCart"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class UdlejningerTent(ListView):
    template_name = "udlejningTent.html"
    allow_empty = True
    queryset = UdlejningTent.objects.filter(
        dateFrom__gte=timezone.now() - datetime.timedelta(days=30)
    )
    context_object_name = "udlejningTent"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

udlejning/templates/udlejning.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap5 bootstrap_icons %}
{% load is_udlejning_with_user compare_udlejning_to_now %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block content %}
<h2 id="rental">
	{% translate "Reservation af fadølsanlæg" %}
	<a href="#rental" class="section-link">#</a>
</h2>
{% if udlejninger %}
<i>
	{% translate "Fadølsanlæggene er allerede reserveret følgende dage:" %}
</i>
<table class="table table-striped">
	<thead>
		<tr>
			<th class="col-md-4">{% translate "Dato" %}</th>
			<th class="col-md-2">{% translate "Reserveret af" %}</th>
			<th class="col-md-2">{% translate "Anlæg" %}</th>
			<th class="col-md-3">{% translate "Ansvarlige" %}</th>
			{% if user.is_staff %}
				<th class="hidden-xs col-md-1"></th>
			{% endif %}
		</tr>
	</thead>
	<tbody>
    {% for udlejning in udlejninger %}
		{% with udlejningComparedToCurrentWeek=udlejning|compare_udlejning_to_now udlejningIsWithUser=udlejning|is_udlejning_with_user:user %}
		<tr>
			<td class="{% if udlejningIsWithUser %}bg-info{% endif %} {% if not udlejningComparedToCurrentWeek %}text-secondary{% endif %}">
				{{ udlejning.dateFrom }}
				{% if udlejning.dateTo %}
					- {{ udlejning.dateTo }}
				{% endif %}
			</td>
			<td class="{% if udlejningIsWithUser %}bg-info{% endif %} {% if not udlejningComparedToCurrentWeek %}text-secondary{% endif %}">
				{{ udlejning.whoReserved }}
			</td>
			<td class="{% if udlejningIsWithUser %}bg-info{% endif %} {% if not udlejningComparedToCurrentWeek %}text-secondary{% endif %}">
				{% if udlejning.draftBeerSystem %} {{ udlejning.get_draftBeerSystem_display }} {% else %} {% translate "Uspecificeret" %} {% endif %}{% translate "anlæg" %}
			</td>
			<td class="{% if udlejningIsWithUser %}bg-info{% endif %} {% if not udlejningComparedToCurrentWeek %}text-secondary{% endif %}">
				{% if udlejning.bartendersInCharge %}
					{% for bartender in udlejning.bartendersInCharge.all %}
						{{ bartender.name }}{% if not forloop.last %}, {% endif %}
					{% endfor %}
				{% else %}
					{% translate "Ikke angivet" %}
				{% endif %}
			</td>
			{% if user.is_staff %}
			<td class="{% if udlejningIsWithUser %}bg-info{% endif %}">
				<a class="common" href="/admin/udlejning/udlejning/{{ udlejning.id }}">
					{% translate "Edit" %}
				</a>
			</td>
			{% endif %}
		</tr>
		{% endwith %}
	{% endfor %}
	</tbody>
</table>
{% else %}
<div class="alert alert-light" role="alert">
  	{% translate "Anlæggene er p.t. ikke reserveret på noget tidspunkt." %}
</div>
{% endif %}
<p>
	{% translate "Hvis vores anlæg ikke allerede er udlånt, kan du låne det ved at udfylde" %}
	<a class="common" href="#rentingform">{% translate "ansøgningsformularen" %}</a> {% translate "nederst på denne side." %}
</p>

<h3 id="rules">
	{% translate "Regler for udlån" %}
	<a href="#rules" class="section-link">#</a>
</h3>

<p>
	{% translate "Anlæg udlånes kun til" %} <b>{% translate "interne arrangementer" %}</b> {% translate "eller til" %} <b>{% translate "arrangementer med tilknytning til baren" %}</b>.
</p>

<div class="row">
	<div class="col-md-6 mb-3">
		<div class="card">
			<div class="card-body">
				<h5 class="card-title">{% translate "Interne arrangementer" %}</h5>
				<p class="card-text">
					{% blocktranslate %}
					Udlån inkluderer opstilling, kopper, kulsyre og skylning af anlægget,
					samt opvask af brugte kopper.
					{% endblocktranslate %}
				</p>
			</div>
			<div class="card-footer">
				{% blocktranslate %}
				Udelukkende arrangementer der finder sted på universitetet. Dette inkluderer:
				{% endblocktranslate %}
				<ul>
					<li>{% translate "Instituttets arrangementer" %}</li>
					<li>{% translate "Specialereceptioner" %}</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="col-md-6 mb-3">
		<div class="card">
			<div class="card-body">
				<h5 class="card-title">{% translate "Arrangementer med tilknytning" %}</h5>
				<p class="card-text">
					{% blocktranslate %}
					Her inkluderer udlån udelukkende oplås og aflås af fadølsanlægget.
					Det vil sige at anlægget skal afhentes i Hopper-0, og afleveres rengjort i Hopper-0.
					{% endblocktranslate %}
				</p>
			</div>
			<div class="card-footer">
				{% blocktranslate %}
				Arrangementer der finder sted på universitetet eller andetsteds, kan være af privat natur. Dette inkluderer:
				{% endblocktranslate %}
				<ul>
					<li>{% translate "Eksterne virksomheder, der af en årsag har tilknytning til baren" %}</li>
					<li>{% translate "Arrangementer af bestyrelsesmedlemmer" %}</li>
					<li>{% translate "I nogle tilfælde, arrangementer af bartendere" %}</li>
				</ul>
			</div>
		</div>
	</div>
</div>

<p>
	{% blocktranslate %}
	Vil man af andre grunde gerne låne anlægget, eller ønsker man også bartendere til bemanding af baren, kan man sende en forespørgelse til
	{% endblocktranslate %}
	<a class="common" href="mailto:best@{{ DOMAIN }}">best@{{ DOMAIN }}</a>.
</p>

<div class="card mb-3">
	<div class="card-body">
		<h5 class="card-title">{% translate "Anmod om udlejning i god tid" %}</h5>
		<p class="card-text">
			{% blocktranslate %}
			Når du låner et anlæg, skal der på udlåningsdagen samt ved tilbagelevering,
			være et bestyrelsesmedlem tilgængelig, der står for det praktiske og kunne låse op.
			Vi er alle frivillige og har studie og jobs ved siden af vores bestyrelsesarbejde,
			og vi kan derfor ikke garantere, at kunne stille et bestyrelsesmedlem til rådighed.
			{% endblocktranslate %}
		</p>
		<p class="card-text">
			{% translate "Derfor skal du, for at være sikker på at kunne låne anlægget" %},
			<b>{% translate "skrive mindst 7 dage i forvejen" %}</b>.
		</p>
	</div>
</div>

<h3 id="prices">
	{% translate "Priser" %}
	<a href="#prices" class="section-link">#</a>
</h3>

<p>
	<i>{% translate "Vi tager forbehold for eventuelle fejl, i de anførte priser." %}</i>
</p>

<div class="card mb-3">
	<div class="card-header">
		{% translate "Der betales pr. åbnet fustage." %}
	</div>
	<ul class="list-group list-group-flush">
		<li class="list-group-item">
			{% translate "Vi kan skaffe fustager fra Aarhus Bryghus, så tag et kig på deres udvalg," %}
			<a class="common" href="https://aarhusbryghus.dk/vare-kategori/lej-fadoel/fadoelsudvalg/" rel="external" target="_blank">{% translate "her" %} {% bs_icon 'box-arrow-up-right' size='0.75em' %}</a>,
			{% translate "og check hvad der eventuelt er i sæson." %}<br>
			{% translate "Vores priser følger dem, Aarhus Bryghus har på deres hjemmeside, men vi tager forbehold for ændringer." %}
		</li>
		<li class="list-group-item">
			{% translate "Vi kan også skaffe Magners Cider på fustage for" %} <i>1500</i> {% translate "kr. pr. fustage." %}
		</li>
		<li class="list-group-item">
			{% translate "Der kan tilkøbes engangs plastikkopper for" %} <i>150</i> {% translate "kr. pr. rulle af 50 stk.." %}
			{% translate "Ellers kan man få lov at låne vores genanvendelige plastikkopper." %}
		</li>
		<li class="list-group-item">
			{% translate "Pris for gas efter aftale." %}
		</li>
		<li class="list-group-item">
			{% translate "Derudover kan vi også levere sodavand og chips. Sodavand koster " %} <i>10</i> {% translate "kr. pr. stk. og chips koster " %} <i>20</i> {% translate "kr. pr. pose." %}
		</li>
	</ul>
	<div class="card-footer">
		{% translate "Priser er inklusiv moms." %}
	</div>
</div>

<h3 id="rentingform">
	{% translate "Ansøgninsformular" %}
	<a href="#rentingform" class="section-link">#</a>
</h3>
<form method="post" action="/{{ LANGUAGE_CODE }}/udlejning/#rentingform">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
		{% translate "Indsend" as BUTTON_TEXT %}
		<button type="submit" class="btn btn-primary">
			{% bs_icon 'send-fill' size='1.0em' %} {{ BUTTON_TEXT }}
		</button>
	{% endbuttons %}
</form>
{% endblock %}