api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import (
    BartenderViewSet,
    BeerTypeViewSet,
    BreweryViewSet,
    IsBartenderView,
    ItemViewSet,
    LastModifiedView,
    PrintStatusView,
    TokenAuthView,
)

router = routers.DefaultRouter()
router.register(r"items", ItemViewSet, "items")
router.register(r"breweries", BreweryViewSet, "breweries")
router.register(r"beerTypes", BeerTypeViewSet)
router.register(r"bartenders", BartenderViewSet)

urlpatterns = [
    path("auth/", TokenAuthView.as_view(), name="token-auth"),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("last-modified/", LastModifiedView.as_view(), name="last-modified"),
    path("is-bartender/<username>/", IsBartenderView.as_view(), name="is_bartender"),
    path("print_status/<job_id>/", PrintStatusView.as_view(), name="print_status"),
]

urlpatterns += router.urls

events/urls.py
from django.urls import path, re_path

from events.views import EventFeed, Events, EventView

urlpatterns = [
    path("", Events.as_view(), name="events"),
    re_path(r"^(?P<event_id>\d+)$", EventView.as_view(), name="event"),
]

items/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Item(models.Model):
    brewery = models.ForeignKey(
        "Brewery", on_delete=models.SET_NULL, null=True, blank=True
    )
    type = models.ForeignKey(
        "BeerType", on_delete=models.SET_NULL, null=True, blank=True
    )
    name = models.CharField(max_length=140, verbose_name=_("Name"))
    description = models.TextField(blank=True, verbose_name=_("Description"))
    country = models.CharField(
        blank=True, max_length=140, verbose_name=_("Country of origin")
    )
    priceInDKK = models.DecimalField(
        max_digits=9 + 2, decimal_places=2, verbose_name=_("Price (DKK)")
    )
    abv = models.FloatField(null=True, blank=True, verbose_name=_("Alcohol by volume"))
    container = models.CharField(
        null=True,
        blank=True,
        max_length=140,
        verbose_name=_("Container"),
        help_text=_("E.g., 'Bottle', 'Can', 'Keg'"),
    )
    volumeInCentiliters = models.IntegerField(
        null=True, blank=True, verbose_name=_("Volume in centiliters")
    )
    bestBefore = models.DateField(null=True, blank=True, verbose_name=_("Best before"))
    inStock = models.BooleanField(default=True, verbose_name=_("In stock"))
    glutenFree = models.BooleanField(default=False, verbose_name=_("Gluten free"))
    nonAlcoholic = models.BooleanField(default=False, verbose_name=_("Non-alcoholic"))
    image = models.ImageField(
        upload_to="items", blank=True, null=True, verbose_name=_("Image")
    )
    barcode = models.CharField(
        max_length=255, unique=True, null=True, blank=True, verbose_name=_("Barcode")
    )
    link = models.CharField(max_length=255, blank=True, verbose_name=_("Link"))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    lastModified = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        if self.brewery:
            return f"{self.brewery} - {self.name}"
        return self.name

    def latex_safe_name(self):
        return self.name.replace("&", "\\amp").replace("'", "`")

    def save(self, *args, **kwargs):
        # Ensure empty barcode is represented as NULL and not ''
        # to enforce the unique constraint
        if not self.barcode:
            self.barcode = None

        # Remove from shelves when going out of stock
        if self.pk:  # Only for existing items (not new ones)
            try:
                old_item = Item.objects.get(pk=self.pk)
                if old_item.inStock and not self.inStock:
                    # Import here to avoid circular import
                    from items.models import ShelfItem

                    ShelfItem.objects.filter(item=self).delete()
            except Item.DoesNotExist:
                pass

        super().save(*args, **kwargs)

    @property
    def current_amount(self):
        latest_entry = self.entries.order_by("-snapshot__datetime").first()
        if latest_entry:
            return latest_entry.amount
        else:
            return 0


class Shelf(models.Model):
    name = models.CharField(max_length=140)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class ShelfItem(models.Model):
    shelf = models.ForeignKey(
        Shelf, on_delete=models.CASCADE, related_name="shelf_items"
    )
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="shelf_items")
    order = models.PositiveIntegerField(default=0)
    added_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("order", "item__name")
        unique_together = ("shelf", "item")

    @property
    def glutenFree(self):
        return self.item.glutenFree

    @property
    def nonAlcoholic(self):
        return self.item.nonAlcoholic


class BeerType(models.Model):
    name = models.CharField(max_length=140)
    description = models.TextField(blank=True)
    link = models.CharField(blank=True, max_length=255)

    def __str__(self):
        return self.name


class Brewery(models.Model):
    name = models.CharField(max_length=140)
    description = models.TextField(blank=True)
    website = models.CharField(blank=True, max_length=255)

    class Meta:
        verbose_name_plural = "Breweries"

    def __str__(self):
        return self.name


class InventorySnapshot(models.Model):
    datetime = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.datetime)


class InventoryEntry(models.Model):
    amount = models.PositiveIntegerField()
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="entries")
    snapshot = models.ForeignKey(
        InventorySnapshot, on_delete=models.CASCADE, related_name="entries"
    )

    def __str__(self):
        return f"{self.item}: {self.amount}"

events/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import EventChoiceOption, EventResponse


class SelectWithDisabledOptions(forms.Select):
    def __init__(self, *args, is_enabled, **kwargs):
        super().__init__(*args, **kwargs)
        self.is_enabled = is_enabled

    def create_option(self, *args, **kwargs):
        option = super().create_option(*args, **kwargs)
        option["attrs"]["disabled"] = not self.is_enabled(option)
        return option


class EventResponseForm(forms.Form):
    ATTENDING_CHOICES = (
        (None, _("Vælg")),
        (True, _("Deltager")),
        (False, _("Deltager ikke")),
    )

    def _to_bool(self, s):
        if s == "False":
            return False
        elif s == "True":
            return True
        else:
            return None

    def _get_choice_field(self, choice):
        return f"choice_{choice.id}"

    def _option_enabled(self, option):
        if not option["value"]:
            return True

        obj = EventChoiceOption.objects.get(id=option["value"].value)
        return obj.can_bartender_choose(self.bartender)

    def __init__(self, *args, event, bartender, **kwargs):
        super().__init__(*args, **kwargs)

        self.event = event
        self.bartender = bartender

        try:
            event_response = EventResponse.objects.get(event=event, bartender=bartender)
        except EventResponse.DoesNotExist:
            event_response = None

        attending_choices = self.ATTENDING_CHOICES
        if event_response:
            attending_choices = self.ATTENDING_CHOICES[1:]

        self.fields["attending"] = forms.TypedChoiceField(
            label=_("Deltager"), choices=attending_choices, coerce=self._to_bool
        )
        for field in self.fields.values():
            field.widget.attrs.update({"class": "form-control"})

        if event_response:
            self.fields["attending"].initial = event_response.attending

        for choice in event.event_choices.all():
            field = forms.ModelChoiceField(
                label=choice.name,
                queryset=choice.options,
                required=False,
                widget=SelectWithDisabledOptions(is_enabled=self._option_enabled),
            )
            field.widget.attrs.update({"class": "form-control"})
            if event_response:
                field.initial = event_response.get_option(choice)

            self.fields[self._get_choice_field(choice)] = field

        if event.deadline_exceeded():
            for field in self.fields.values():
                field.disabled = True

    def clean(self):
        super().clean()
        if self.cleaned_data["attending"]:
            for choice in self.event.event_choices.all():
                field = self._get_choice_field(choice)

                option = self.cleaned_data.get(field)

                if not option:
                    self.add_error(
                        field,
                        _("Du skal udfylde %(choice_name)s, når du deltager")
                        % {"choice_name": choice.name},
                    )
                    continue

                if not option.can_bartender_choose(self.bartender):
                    self.add_error(
                        field,
                        _(
                            "Der er for mange der har valgt %(option_option)s. Vælg noget andet."
                        )
                        & {"option_option": option.option},
                    )

    def save(self):
        attending = self.cleaned_data["attending"]
        response, _ = EventResponse.objects.update_or_create(
            event=self.event,
            bartender=self.bartender,
            defaults={
                "attending": attending,
            },
        )

        response.selected_options.clear()
        if attending:
            for choice in self.event.event_choices.all():
                response.set_option(self.cleaned_data[self._get_choice_field(choice)])

        return response

events/views.py
from datetime import date, timedelta

from constance import config
from django.conf import settings
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponseBadRequest, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from django_ical.views import ICalFeed

from bartenders.models import Bartender

from .forms import EventResponseForm
from .models import CommonEvent, Event

DEFAULT_EVENTS_PER_PAGE = 3


class Events(TemplateView):
    template_name = "events.html"

    def get_bartender(self):
        if not self.request.user.is_authenticated:
            return None

        try:
            return Bartender.objects.get(email=self.request.user.email)
        except Bartender.DoesNotExist:
            return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if config.SHOW_COMMON_EVENTS:
            todayish = date.today() - timedelta(days=1)
            yearAgo = date.today() - timedelta(days=365)

            futureEvents = CommonEvent.objects.filter(date__gt=(todayish))
            pastEvents = CommonEvent.objects.filter(
                date__range=(yearAgo, todayish)
            ).reverse()
            context["futureEvents"] = futureEvents
            context["pastEvents"] = pastEvents

        events_per_page = self.request.GET.get("events_per_page")
        if (
            not events_per_page
            or events_per_page == "0"
            or events_per_page == ""
            or not events_per_page.isdigit()
            or int(events_per_page) <= 0
        ):
            events_per_page = DEFAULT_EVENTS_PER_PAGE
        context["events_per_page"] = events_per_page

        events = Event.objects.defer(
            "description", "bartender_whitelist", "bartender_blacklist"
        )

        paginator_events = Paginator(events, events_per_page)

        event_page = self.request.GET.get("event_page", 1)
        event_page_obj = paginator_events.get_page(event_page)
        context["event_page_obj"] = event_page_obj

        bartender = self.get_bartender()

        seen_years = set()
        events_data = []

        for event in event_page_obj:
            data = {"event": event}
            if event.year not in seen_years:
                data["year"] = event.year
                seen_years.add(event.year)
            events_data.append(data)

        context["bartender"] = bartender
        context["events_data"] = events_data

        return context


class EventFeed(ICalFeed):
    product_id = "-//fredagscafeen.dk//Events//EN"
    timezone = "UTC"
    file_name = "events.ics"
    title = _("Bartender Events")

    def items(self):
        return Event.objects.all()

    def item_title(self, event):
        return event.name

    def item_location(self, event):
        return event.location

    def item_start_datetime(self, event):
        return event.start_datetime

    def item_end_datetime(self, event):
        return event.end_datetime

    def item_description(self, event):
        tilmeldingsfrist = _("Tilmeldingsfrist")
        return f"""{tilmeldingsfrist}: {event.response_deadline}

{event.description}"""

    def item_link(self, event):
        return f"{settings.SELF_URL}events/"

    def item_guid(self, event):
        return f"event-{event.pk}@fredagscafeen.dk"


class CommonEventFeed(ICalFeed):
    product_id = "-//fredagscafeen.dk//CommonEvents//EN"
    timezone = "UTC"
    file_name = "common_events.ics"
    title = _("Common Events")

    def items(self):
        return CommonEvent.objects.all()

    def item_title(self, event):
        return event.title

    def item_start_datetime(self, event):
        return event.date

    def item_end_datetime(self, event):
        return event.date

    def item_description(self, event):
        return event.description

    def item_link(self, event):
        return f"{settings.SELF_URL}common-events/"

    def item_guid(self, event):
        return f"common-event-{event.pk}@fredagscafeen.dk"


class EventView(TemplateView):
    template_name = "event.html"

    def get_bartender(self):
        if not self.request.user.is_authenticated:
            return None

        try:
            return Bartender.objects.get(email=self.request.user.email)
        except Bartender.DoesNotExist:
            return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["load_no_answers"] = self.request.GET.get("load_no_answers")

        event_id = self.request.resolver_match.kwargs["event_id"]
        event = get_object_or_404(Event, id=event_id)

        bartender = self.get_bartender()

        may_attend = False
        if bartender:
            may_attend = event.may_attend(bartender)

        if may_attend:
            context["form"] = EventResponseForm(event=event, bartender=bartender)

        context["bartender"] = bartender
        context["event"] = event
        context["may_attend"] = may_attend

        return context

    def post(self, request, *args, **kwargs):
        try:
            event_id = request.POST.get("event_id")
            event = Event.objects.get(id=event_id)
        except Event.DoesNotExist:
            return HttpResponseBadRequest(_("Event with id does not exist"))

        bartender = self.get_bartender()
        if not bartender or not event.may_attend(bartender):
            return HttpResponseForbidden(_("Not logged in as an active bartender"))

        form = EventResponseForm(request.POST, event=event, bartender=bartender)
        if not form.is_valid():
            for error in form.errors.values():
                messages.error(request, f"{error}")
            return redirect("event", event_id)

        form.save()

        messages.success(
            request,
            _("Opdateret tilmelding til %(event_name)s") % {"event_name": event.name},
        )
        return redirect("event", event_id)

web/templates/contact.html
{% extends 'base.html' %}

{% block content %}

<h2>Generel info</h2>

<p>Fredagscaféen befinder sig kælderen i Nygaard-bygningen på Institut for Datalogi, Helsingforsgade 14, 8200 Aarhus N.
Baren har åbent <em>alle</em> fredage fra klokken 15.00 til vi lukker.</p>

<hr>

<h2>Postadresse</h2>
<p>
Vores postadresse er:<br>
Fredagscaféen<br>
Åbogade 34<br>
8200 Aarhus N
</p>

<hr>

<h2>CVR</h2>
<p>Vores CVR-nr er: <a href="https://datacvr.virk.dk/data/visenhed?enhedstype=virksomhed&id=27973647">27973647</a></p>

<hr>

<h2>E-mail</h2>
Bestyrelsen kan kontaktes på <a href="mailto:best@fredagscafeen.dk">best@fredagscafeen.dk</a>



{% endblock %}

web/templates/events.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block content %}

<h2>Bartender events</h2>

<p><a href="{% url 'event_feed' %}">Tilføj til kalender</a></p>

{% if not bartender %}
<p><b>Du er ikke logget ind som bartender og kan derfor ikke tilmelde dig events.</b></p>
{% elif not bartender.isActiveBartender %}
<p><b>{{ user.email }} er ikke aktiv bartender og kan derfor ikke tilmelde sig events.</b></p>
{% endif %}

{% for events_data in events_data %}
	{% with events_data.event as event %}
		<h3>{{ event.start_datetime.date }} - {{ event.name }}</h3>
		<p><b>{{ event.start_datetime }}</b> til <b>{{ event.end_datetime }}</b>.</p>
		<p><b>Tilmeldingsfrist:</b> {{ event.response_deadline }}{% if not enabled %} (for sent){% endif %}</p>
		<p><b>Lokation:</b> {{ event.location }}</p>
		<p><b>Beskrivelse:</b></p>
		<p>{{ event.description }}</p>
		{% if events_data.form %}
			<h4>Tilmelding</h4>
			<form method="post">
				<fieldset{% if not events_data.enabled %} disabled{% endif %}>
					{% csrf_token %}
					<input type="hidden" name="event_id" value="{{ event.id }}">
					{% bootstrap_form events_data.form %}
					{% buttons %}
						{% bootstrap_button "Gem" button_type="submit" icon="floppy-disk" button_class="btn-primary" %}
					{% endbuttons %}
				</fieldset>
			</form>
		{% endif %}
	{% endwith %}
{% endfor %}

<script>
function updateRequired() {
	$('form').each(function (i, form) {
		var attending = $(form).find('[name="attending"]').val() === 'True';
		$(form).find('select[name!="attending"]').each(function (i, select) {
			$(select).prop('required', attending);
			$(select).prop('disabled', !attending);
		});
	});
}
$('[name="attending"]').change(updateRequired);
updateRequired();
</script>

{% endblock %}

web/templates/foo.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Fredagscaféen</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/tablesorter/2.17.4/js/jquery.tablesorter.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
    <script>
        (function(document) {
            'use strict';

            var LightTableFilter = (function(Arr) {

                var _input;

                function _onInputEvent(e) {
                    _input = e.target;
                    var tables = document.getElementsByClassName(_input.getAttribute('data-table'));
                    Arr.forEach.call(tables, function(table) {
                        Arr.forEach.call(table.tBodies, function(tbody) {
                            Arr.forEach.call(tbody.rows, _filter);
                        });
                    });
                }

                function _filter(row) {
                    var text = row.textContent.toLowerCase(), val = _input.value.toLowerCase();
                    row.style.display = text.indexOf(val) === -1 ? 'none' : 'table-row';
                }

                return {
                    init: function() {
                        var inputs = document.getElementsByClassName('light-table-filter');
                        Arr.forEach.call(inputs, function(input) {
                            input.oninput = _onInputEvent;
                        });
                    }
                };
            })(Array.prototype);

            document.addEventListener('readystatechange', function() {
                if (document.readyState === 'complete') {
                    LightTableFilter.init();
                }
            });

        })(document);
    </script>
    <style>
        .form-control {
            background-color: lightgreen;
        }

        .price
        {
            background-color: green;
            color: white;
            font-weight: bold;
        }
    </style>
</head>
<body>
<div id="input-group">
    <input type="search" class="light-table-filter form-control" data-table="order-table" placeholder="Search">
</div>
<div>
    <table class="table table-striped light-table-filter" data-table="order-table" id="items">
    <thead>
        <tr>
            <th></th>
            <th>Pris</th>
        </tr>
        </thead>
    <tbody>
    {% for item in items %}
        <tr>
            <td>
                {% if item.brewery %}
                    {{ item.brewery }} -
                {% endif %}
                {{ item.name }} ({{ item.get_container_display }})
            </td>
        <td class="price">
            {{ item.priceInDKK }}
        </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
</div>

web/templates/jquery.html
<script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
<script>
    // Prevent auto-execution of scripts when no explicit dataType was provided (See gh-2432)
    jQuery.ajaxPrefilter( function( s ) {
        if ( s.crossDomain ) {
            s.contents.script = false;
        }
    } );
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/js/jquery.tablesorter.min.js" integrity="sha384-5DBGnz9O9jxqph+/AFCwYJNAb4rEJXYbRT4M6WYtLfzjIPX6kKiBIKKvsW5x7gak" crossorigin="anonymous"></script>

web/templates/login.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap5 %}

{% block content %}

<form method="post">
{% csrf_token %}
{% bootstrap_form form %}
{% buttons %}
    {% translate "Log ind" as BUTTON_TEXT %}
    <button type="submit" class="btn btn-primary" style="margin-top: 15px; margin-bottom: 15px;">
        {{ BUTTON_TEXT }}
    </button>
{% endbuttons %}
</form>

{% endblock %}

web/templates/plain_base.html
<!doctype html>
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}" data-bs-theme="light">
<head>
    {% load static %}
    <title>Fredagscaféen</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>

    {% include "jquery.html" %}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
    <script type="text/javascript" src="{% static 'js/darkModeState.js' %}"></script>
    <script> window.onload = setTheme()</script>

    <script src="{% static 'js/memes.js' %}"></script>
    {% block extrahead %}{% endblock %}
</head>
<body>
    {% block body_content %}{% endblock %}
    <script>
        window.onload = setThemeToggle()
    </script>
</body>
</html>

web/templates/secrets_admin.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% load static %}
{% load bootstrap_icons %}
{% block content %}
<div class="overflow: auto;">
	<table style="width: 100%;">
		<tr>
			<th></th>
			<th>{% translate "Django key" %}</th>
			<th>{% translate "Beskrivelse" %}</th>
			<th>{% translate "Brugernavn" %}</th>
			<th>{% translate "Kode" %}</th>
			<th>{% translate "Link" %}</th>
		</tr>
		{% for secret in secrets %}
			{% with key=secret.key description=secret.description username=secret.username value=secret.value url=secret.url role=secret.role %}
				{% if role != None %}
				<tr style="background-color:rgba(51, 122, 183, 0.5);">
					<th colspan="6">{{ role }}:</th>
				</tr>
				{% else %}
				<tr></tr>
				{% endif %}
				<td></td>
				<td style="max-width: 75px; overflow-x: scroll;"><code>{{ key }}</code></td>
				<td style="max-width: 200px; overflow-x: auto; word-break: break-all;">{{ description }}</td>
				<td style="max-width: 300px; overflow-x: auto; word-break: break-all;">
					{% if username != None %}
						<code>{{ username }}</code>
					{% endif %}
				</td>
				<td style="max-width: 300px; overflow-x: auto; word-break: break-all;">
					{% if value != None and value != "" %}
						<code>{{ value }}</code>
						<button type="submit" class="copyButton" style="border: none; background-color: transparent;" >
							<a style="color: #337ab7;" onMouseOver="this.style.color='red'" onMouseOut="this.style.color='#337ab7'" >{% bs_icon 'copy' size='1.0em' %}</a>
						</button>
					{% endif %}
				</td>
				<td>
					{% if url != None %}
						<a href="{{ url }}">Login</a>
					{% endif %}
				</td>
			{% endwith %}
		{% endfor %}
	</table>
</div>
<script>
	const copyButtons = document.getElementsByClassName('copyButton');
	for(var index=0; index < copyButtons.length; index++){
		const element = copyButtons[index];
		element.addEventListener('click', function(){
			const parent = element.parentElement;
			const text = parent.firstElementChild.textContent;
			navigator.clipboard.writeText(text).then(() => {
				/* Resolved - text copied to clipboard successfully */
			},() => {
				/* Rejected - text failed to copy to the clipboard */
			});
		});
	}
</script>
{% endblock %}

web/templates/swap_admin.html
{% extends "admin/base_site.html" %}
{% block content %}
<form action="?step={{ next_step }}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% if form_step == 0 %}Next{% else %}Submit{% endif %}" />
	{% if form_step == 1 %}
		<input type="button" value="Back" onclick="window.location.search = ''" />
	{% endif %}
</form>
{% endblock %}